import type { Metadata } from "next";

import "./globals.css";
import { Raleway, Poppins } from "next/font/google";

import ReactQueryProvider from "./components/queryClientProvider";
const raleway= Raleway({
  subsets:['latin'],
  variable:"--font-secondary"
})
const poppins= Poppins({
  subsets:['latin'],
  weight:['400','700'],
  variable:"--font-primary"
})
export const metadata: Metadata = {
  title: "talkative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} ${poppins.className} antialiased`}
      >
       <ReactQueryProvider>
          {children}
       </ReactQueryProvider> 
        
      </body>
    </html>
  );
}
